<?php

namespace AppBundle\Repository;

/**
 * AthleteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AthleteRepository extends \Doctrine\ORM\EntityRepository
{
}
