<?php

namespace AppBundle\Repository;

/**
 * CompetitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitorRepository extends \Doctrine\ORM\EntityRepository
{
}
